[build-system]
requires = ["maturin>=0.13.1,<0.14"]
build-backend = "maturin"

[tool.black]
line-length = 79
target_version = ['py310']

[tool.maturin]
cargo-extra-args = "--features pyo3/extension-module"
